/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package latarnie;

import java.io.FileNotFoundException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JCheckBox;
import static latarnie.Latarnie.col;
import static latarnie.Latarnie.row;

/**
 *
 * @author Lenovo
 */
public class Teren extends javax.swing.JFrame {
static JCheckBox[][] cos = new JCheckBox[12][12];
static Pole[][] tab1;
    /**JCheckBox[][] cos = new JCheckBox[10][10];
     * Creates new form Teren
     */
    public Teren() {
        initComponents();
        
        
     
        // = new JCheckBox[10][10]; //;;= new jCheckBox[][];
        //cos[0][0] = javax.swing.JCheckBox kov = new javax.swing.JCheckBox();//jCheckBox1;
        //cos[0][0] = 
        
        //cos[0][0] = new JCheckBox();
        //this.add(cos[0][0]);
        int y=50,x=50;
         for (int i=0; i<12; i++) 
        {
            y=50;
        for (int j=0; j<12; j++)
            {
                 
                cos[i][j] = new JCheckBox();
                cos[i][j].setBounds(x, y, 20, 20);
                add(cos[i][j]);
                cos[i][j].setVisible(false);
                //cos[i][j].setEnabled(false);
                y = y+20;
            }
         x=x+20;
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Recznie");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("z pliku");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("WYczyść");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(212, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addGap(34, 34, 34)
                        .addComponent(jButton1))
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(237, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton3))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Pole[][] tab1 = new Pole[12][12];  
        
        
        for (int k = 0; k < 12; k++) {
            for (int l = 0; l < 12; l++) {
                tab1[l][k] = new Pole(0,0, false);

            }

        }
        
        for (int i = 0; i < 12; i++) {
            for (int j = 0; j < 12; j++) {
                if(cos[i][j].isSelected())
                {
                    tab1[i][j] = new Pole(1,1,false);
                }
//                else
//                {
//                    tab1[i][j] = new Pole(0,0,false);
//                }
                
            }
            
        }
        System.out.println("///////////////////////////////////////////////////");
         for ( int i = 1; i < 11; i++) {
            for (int j = 1; j < 11; j++) {
                System.out.print(tab1[j][i].pole + " ");
            }
            System.out.println("");
        }
        Latarnie.pokrycie(tab1);
        Latarnie.usuwanie(tab1);
         System.out.println("///////////////////////////////////////////////////");
         for ( int i = 1; i < 11; i++) {
            for (int j = 1; j < 11; j++) {
                System.out.print(tab1[j][i].pole + " ");
            }
            System.out.println("");
        } System.out.println("///////////////////////////////////////////////////");
         for ( int i = 1; i < 11; i++) {
            for (int j = 1; j < 11; j++) {
                System.out.print(tab1[j][i].latarnia + " ");
            }
            System.out.println("");
            Latarnie.wyswietlanie(tab1);
            
            
    }//GEN-LAST:event_jButton1ActionPerformed
    }
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
     Pole[][] tab1 = new Pole[12][12];  
        
        
        for (int k = 0; k < 12; k++) {
            for (int l = 0; l < 12; l++) {
                tab1[l][k] = new Pole(0,0, false);

            }

        }
        
        
        try {
        Latarnie.wczytywanie(tab1);
    } catch (FileNotFoundException ex) {
        Logger.getLogger(Teren.class.getName()).log(Level.SEVERE, null, ex);
    }
        System.out.println("ssssssssssssssssssssssssssssssssss");
         for (int i = 1; i < row + 1; i++) {
            for ( int j = 1; j < col + 1; j++) {
                System.out.print(tab1[j][i].latarnia + " ");
            }
            System.out.println("");
        }
        
        
        
        Latarnie.pokrycie(tab1);
        Latarnie.usuwanie(tab1);
        
        
        Latarnie.wyswietlanie(tab1);
        //Latarnie.ustawienie(tab1);
         System.out.println("ssssssssssssssssssssssssssssssssss");
         for (int i = 1; i < row + 1; i++) {
            for ( int j = 1; j < col + 1; j++) {
                System.out.print(tab1[j][i].latarnia + " ");
            }
            System.out.println("");
         }
         
         
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        for (int i = 1; i < 11;i++) {
           for (int j = 1; j < 11; j++) {
            cos[i][j].setVisible(true);
            cos[i][j].setEnabled(true);
            cos[i][j].setSelected(false);
            
        }
            
        }
    }//GEN-LAST:event_jButton3ActionPerformed
    
   
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Teren.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Teren.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Teren.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Teren.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Teren().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    // End of variables declaration//GEN-END:variables
}


